version: '2'
services:
    escribanos-app:
        image: escribanos
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://escribanos-mysql:3306/escribanos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    escribanos-mysql:
        extends:
            file: mysql.yml
            service: escribanos-mysql
